library(ggplot2)
args <- commandArgs(trailingOnly = TRUE)
myData <- read.table(args[1], sep=' ' , header=TRUE, row.names=1)
eigenval <- read.table("final.eigenval")
total <- sum(eigenval)
filename <- paste(args[1], '.pdf', sep='')
pdf(filename, width=8, height=6)
xlabel <- paste('PC1(', round((eigenval$V1[1]/total)*100, 2), '%)', sep='')
ylabel <- paste('PC2(', round((eigenval$V1[2]/total)*100, 2), '%)', sep='')
ggplot(myData, aes(x=pc1, y=pc2, color=X2)) + geom_point() + xlab(xlabel) + ylab(ylabel) 
dev.off()
